<a href="https://colab.research.google.com/github/RosaDeSa/file/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd # Library for Dataframe handling
from sklearn.preprocessing import LabelEncoder # sklear = ML Library
import json # Manage Text data
import folktables # Not in google colab; to use it we have to install it in cloud
# To 
import numpy as np # Numeric values management

ModuleNotFoundError: ignored

In [ ]:
!pip3 install folktables

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting folktables
  Downloading folktables-0.0.12-py3-none-any.whl (17 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.9/dist-packages (from folktables) (1.2.2)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from folktables) (2.27.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (from folktables) (1.4.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from folktables) (1.22.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas->folktables) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas->folktables) (2022.7.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->folktables) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.9/dist-packages (from requests->folktables) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->folktables) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->folktables) (3.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn->folktables) (3.1.0)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-learn->folktables) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn->folktables) (1.1.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas->folktables) (1.16.0)
Installing collected packages: folktables
Successfully installed folktables-0.0.12

In [ ]:
continous_feature_L = [
    "hours-per-week",
    "age",
    "capital-gain",
    "capital-loss",
    "education-num",
]

categorical_feature_L = [
    "workclass",
    "education",
    "marital-status",
    "relationship",
    "race",
    "gender",
    "native-country",
    "occupation",
]

url = 'https://raw.githubusercontent.com/socialfoundations/folktables/main/adult_reconstruction.csv'
df1 = pd.read_csv(url)# Dataset is now stored in a Pandas Dataframe

df1.head()

,hours-per-week,age,capital-gain,capital-loss,workclass,education,education-num,marital-status,relationship,race,gender,native-country,income,occupation
0,20,40,0,0,Private,Bachelors,13,Married-civ-spouse,Wife,White,Female,United-States,49100,Tech-support
1,40,21,0,0,Private,Some-college,10,Divorced,Own-child,White,Male,United-States,11500,Craft-repair
2,10,17,0,0,Private,11th,7,Never-married,Own-child,White,Male,United-States,2600,Other-service
3,50,51,0,0,Private,HS-grad,9,Married-civ-spouse,Husband,Asian-Pac-Islander,Male,Cambodia,38997,Sales
4,38,28,0,0,Private,Bachelors,13,Never-married,Not-in-family,White,Male,?,41400,Exec-managerial